/**
 * Pure helpers of the locator strategy. They are inlined into the in-page
 * collector script by source (Function.prototype.toString), so each one must
 * be self-contained: no imports, no closures over module state.
 */

/** Ids generated by frameworks change between renders and must not become locators. */
export function isStableId(id: string): boolean {
  if (!id || id.length > 64) return false
  if (/^(:r|radix-|mui-|ember\d|react-|headlessui-|v-|__|ng-)/.test(id)) return false
  if (/\d{4,}/.test(id)) return false
  if (/[-_][0-9a-f]{6,}$/i.test(id)) return false
  if (/^[0-9]/.test(id)) return false
  return true
}

/** The implicit ARIA role of a tag, for the role+name locator. */
export function implicitRole(tag: string, attrs: { type?: string | null; href?: string | null }): string | null {
  switch (tag) {
    case 'button':
      return 'button'
    case 'a':
      return attrs.href ? 'link' : null
    case 'h1':
    case 'h2':
    case 'h3':
    case 'h4':
    case 'h5':
    case 'h6':
      return 'heading'
    case 'img':
      return 'img'
    case 'nav':
      return 'navigation'
    case 'main':
      return 'main'
    case 'header':
      return 'banner'
    case 'footer':
      return 'contentinfo'
    case 'ul':
    case 'ol':
      return 'list'
    case 'li':
      return 'listitem'
    case 'table':
      return 'table'
    case 'select':
      return 'combobox'
    case 'textarea':
      return 'textbox'
    case 'dialog':
      return 'dialog'
    case 'input': {
      const t = (attrs.type || 'text').toLowerCase()
      if (t === 'button' || t === 'submit' || t === 'reset' || t === 'image') return 'button'
      if (t === 'checkbox') return 'checkbox'
      if (t === 'radio') return 'radio'
      if (t === 'range') return 'slider'
      if (t === 'hidden' || t === 'file' || t === 'color' || t === 'date' || t === 'time' || t === 'datetime-local' || t === 'month' || t === 'week') return null
      return 'textbox'
    }
    default:
      return null
  }
}

/** Escape a value for use inside a double-quoted attribute selector. */
export function escapeAttributeValue(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')
}

export function collapseWhitespace(text: string): string {
  return text.replace(/\s+/g, ' ').trim()
}
