#!/usr/bin/env node
/**
 * Bundle the <elastishot-viewer> custom element into a single ESM file for
 * the "browser" export condition, and embed the same code as a string in
 * src/report/viewer-bundle.ts so generated reports can inline it.
 *
 *   node scripts/build-viewer.mjs
 *
 * When src/viewer/index.ts does not exist yet, an empty bundle is written so
 * the rest of the build still works.
 */

import fs from 'node:fs'
import { build } from 'esbuild'

const ENTRY = 'src/viewer/index.ts'
const OUT_FILE = 'dist/viewer/elastishot-viewer.js'
const BUNDLE_TS = 'src/report/viewer-bundle.ts'
const HEADER = '// GENERATED by scripts/build-viewer.mjs from src/viewer. Do not edit by hand.\n'

function writeBundleModule(code) {
  fs.mkdirSync('src/report', { recursive: true })
  fs.writeFileSync(BUNDLE_TS, `${HEADER}export const viewerBundle: string = ${JSON.stringify(code)}\n`)
}

if (!fs.existsSync(ENTRY)) {
  writeBundleModule('')
  console.log(`viewer entry ${ENTRY} not found; wrote an empty ${BUNDLE_TS}`)
  process.exit(0)
}

const result = await build({
  entryPoints: [ENTRY],
  bundle: true,
  format: 'esm',
  target: ['es2022'],
  minify: true,
  legalComments: 'none',
  write: false,
})
const code = result.outputFiles[0].text
fs.mkdirSync('dist/viewer', { recursive: true })
fs.writeFileSync(OUT_FILE, code)
writeBundleModule(code)
console.log(`viewer bundle: ${(code.length / 1024).toFixed(1)} KB -> ${OUT_FILE}, ${BUNDLE_TS}`)
